from pathlib import Path
import json,datetime,platform,subprocess,sys,hashlib
ROOT=Path(__file__).resolve().parents[1]
def main():
 repo=next(p for p in ROOT.parents if (p/'.git').exists())
 h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
 tracked=[p for dirname in ['src','model','results','verification'] for p in (ROOT/dirname).rglob('*') if p.is_file() and '__pycache__' not in str(p) and p.suffix in ['.py','.cpp','.tex','.json','.csv']]
 data={'run':'R002','model':'Q2-expected-M01-v02-terminal-area-and-radius','algorithm':'A02-continuous-arcs-quadrature-grid-multistart','data':'D01-S1-origin-bearing-east','started_approx_directory_creation':datetime.datetime.fromtimestamp(ROOT.stat().st_birthtime).astimezone().isoformat(),'completed_record_time':datetime.datetime.now().astimezone().isoformat(),'source_model':'../模型讲解稿/第二问模型讲解.tex','source_snapshot':'model/模型快照.tex','model_sha256':h(ROOT/'model/模型快照.tex'),'current_source_matches_snapshot':h(ROOT/'model/模型快照.tex')==h(ROOT.parent/'模型讲解稿/第二问模型讲解.tex'),'baseline_solver':'../R001_期望包围圆面积_原点正东/src/solver.cpp','baseline_solver_sha256':h(ROOT.parent/'R001_期望包围圆面积_原点正东/src/solver.cpp'),'git_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip(),'git_branch':subprocess.check_output(['git','branch','--show-current'],cwd=repo,text=True).strip(),'uncommitted_work':True,'git_note':'Run directory is local and untracked; hash and source files, not HEAD alone, identify this run. No commit or push performed.','working_directory':str(ROOT),'python_executable':sys.executable,'python_version':sys.version,'platform':platform.platform(),'compiler':subprocess.check_output(['clang++','--version'],text=True).splitlines()[0],'compile_command':'clang++ -std=c++17 -O3 src/solver.cpp -o solver','reproduce_command':f'{sys.executable} src/reproduce.py','executed_stages':['C++ compilation','src/search.py','nearopt5 batch level3','src/validate.py','src/verify_geometry.py','src/summarize.py'],'random_seeds':[20260912,20260913,1729],'search_record':json.loads((ROOT/'results/search_summary.json').read_text()),'validation_status':'Numerical and independent checks passed for recorded cases. No certified global optimum.','adoption_status':'Candidate, not team adoption','stop_reason':'Both requested objectives solved and recorded; prescribed checks passed','deferred':'Success/clearance probability optimization and improved objectives','sha256':{str(p.relative_to(ROOT)):h(p) for p in tracked}}
 # JSON is a valid YAML 1.2 document; avoids an additional dependency.
 (ROOT/'manifest.yaml').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 print('manifest.yaml written')
if __name__=='__main__':main()
